import Head from "next/head";
import styles from "@/styles/Home.module.css";
import VoiceAssistant from "./components/VoiceAssistant/VoiceAssistant.component";
import useApp, { HomeProps } from "@/hooks/useApp";

function Home(props: HomeProps) {
  useApp(props);
  return (
    <>
      <Head>
        <title>AI Voice Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <VoiceAssistant />
      </main>
    </>
  );
}
export async function getServerSideProps() {
  // Access the environment variable
  const backendUrl = process.env.BACKEND_URL;

  // Pass the environment variable as a prop
  return {
    props: {
      backendUrl,
    },
  };
}

export default Home;
